### ISSUE TITLE
Sensor data configuration error

### ISSUE THREAD

**Issue by LoganJFisher** [alexander0042/pirate-weather-ha#10]
I successfully got the basic weather info working with:

weather:
  - platform: pirateweather
    api_key: <APIKEY>

However, when I try to use:

sensor:
  - platform: pirateweather
    api_key: <APIKEY>
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

I get a configuration validation error:

Platform error sensor.pirateweather - cannot import name 'SensorEntity' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

Please help.

**Comment by alexander0042** [comment]
Hi,

Thanks for this report!

I think this might be a documentation issue, since when I use the same set of config parameters, it's working for me. This is what my config file looks like- do you see any differences between the formatting and the formatting you're using? Also, did you install via HACS. or manually?

Thanks,
Alexander 
 
![image](https://user-images.githubusercontent.com/26213938/131350548-d4b2c0cc-e609-496d-b396-ab96a7efa18e.png)

**Comment by LoganJFisher** [comment]
The only difference (aside from the api key, obviously) is that I have "space space dash space" before "platform", while you just have four spaces. I tried replacing the dash with a space though, and it still doesn't work.

I installed via HACS.

**Comment by alexander0042** [comment]
Well, it was worth a try starting with the easiest stuff!

I dug into this a little more and I'm wondering what version of Home Assistant you're running? It looks like the "SensorEntity" class that is throwing the error was added in [March 2021](https://github.com/home-assistant/core/pull/48211), which is why it's in this version of the sensor.py file. 

I'm thinking that if you're running an older version, it wouldn't have this Python class, which would explain the error

**Comment by LoganJFisher** [comment]
Ah, that explains it. I'm on core-2021.3.0

I updated a bit ago, and it broke some stuff so I reverted. I guess when I have some time I'll update again and try fixing those things that broke.

**Comment by alexander0042** [comment]
Ok, that's too bad, but at least we know the problem now- I'll add this to the documentation, since that isn't that old of a version! If you'd like to use PirateWeather as a data source, you can always go to the Dark Sky Sensor Python script in your install (from your initial comment it should be somewhere around: `/usr/src/homeassistant/homeassistant/components/sensor` and change the `self.data = forecastio.load_forecast` command to these two lines:

`            forecastString = "https://api.pirateweather.net/forecast/" +  self._api_key + "/" + str(self.latitude) + "," + str(self.longitude) + "?units=" + self.units
            self.data = forecastio.manual(forecastString)`

Which is 95% of what this custom integration does- it's just calling the (incredibly convenient) "manual forecast string" function of the Dark Sky Python library instead of the default one

**Comment by LoganJFisher** [comment]
Thanks for your help!
