### ISSUE TITLE
Incorrect high temperature in daily forecast for current day

### ISSUE THREAD

**Issue by jb1228** [alexander0042/pirate-weather-ha#110]
I am not sure if this is an issue with the API or the HA integration; but in the daily forecast, the high temperature for the current day is correct **_until_** the afternoon/evening after the high temperature is met. The value then seems to change to the MAX value of the next 7 days. 

For instance, this screenshot was taken on May 9th around 1:00 PM showing the correct high temp (70):

<img width="539" alt="Screenshot 2023-05-09 at 12 58 23 PM" src="https://github.com/alexander0042/pirate-weather-ha/assets/37507376/386108a2-f36a-4209-a640-a119fa57319b"><br>

The value then changes to 80, which is the highest value of the 7 day forecast (Thursday). This screenshot was taken May 9th around 6:30 PM: 

<img width="536" alt="Screenshot 2023-05-09 at 6 30 57 PM" src="https://github.com/alexander0042/pirate-weather-ha/assets/37507376/08743ffc-66c5-45fb-88b9-790fbab1b0eb"><br>

I only became aware of this after setting up the `clock-weather-card`, since it is easily noticed.

As an example, here is the card for today (Monday) at 9:14 PM. The high for today was actually only around 74. 

<img width="438" alt="Screenshot 2023-05-15 at 9 14 32 PM" src="https://github.com/alexander0042/pirate-weather-ha/assets/37507376/8ed0f98e-96d6-405f-bf6a-4b222e889a5b">

I realize it is just a minor issue, but I thought I'd make you aware of it. Thank you for your hard work on all of this!

**Comment by cloneofghosts** [comment]
This issue is a PW issue as a result of the temperature min/max/high/low changes in this issue https://github.com/alexander0042/pirateweather/issues/5

This issue has been brought up in https://github.com/alexander0042/pirateweather/issues/23 and https://github.com/alexander0042/pirate-weather-ha/issues/90 so it's something that the developer is aware of. I'm not sure where exactly this issue lies on the priority list after the API gateway change which should hopefully be done soon.

**Comment by bbrendon** [comment]
Yes. This bug is still very annoying. :D

**Comment by cloneofghosts** [comment]
This issue is something that the dev is currently working on and is next in line to be fixed. If you would like to follow along with any progress there are these issues in the processing code repo https://github.com/alexander0042/pirateweather/issues/5 and https://github.com/alexander0042/pirateweather/issues/85.

**Comment by cloneofghosts** [comment]
Since this is a API issue and not a HA issue I'm going to close this for cleanup. If you want to keep updated with this issue you can follow along here alexander0042/pirateweather#5 and alexander0042/pirateweather#85.
