### ISSUE TITLE
Unknown state and icon

### ISSUE THREAD

**Issue by afxefx** [alexander0042/pirate-weather-ha#113]
For the past ~24 hours my state and icon have been showing as unknown. The other stats show correctly (well wind is always higher than actual but just giving that time) though.  I also pulled the api directly, via browser, and it is indeed returning unknown under the currently section.  May just be a fluke but wanted to report regardless.

![Screenshot_20230528-001826](https://github.com/alexander0042/pirate-weather-ha/assets/3475494/4c4caae5-9314-446b-abfd-fb2bfb71e9cc)
![Screenshot_20230528-001845](https://github.com/alexander0042/pirate-weather-ha/assets/3475494/1910e55b-6ee6-4354-9fd8-d139a6acf672)

**Comment by cloneofghosts** [comment]
The V1.5.1 update is causing an issue where only the extended forecast of the extended HRRR forecast is being integrated. It looks like the current conditions are using a mix of HRRR extended data and GFS data.

It looks to me like the precipitation variables, temperature, wind, visibility and humidity are coming from the GFS model whereas everything else is coming from the HRRR extended forecast. Whenever GFS is reporting rain it seems to be confusing the summary/icon calculations and it's returning None instead of Rain in this case.

**Comment by alexander0042** [comment]
Yes, exactly what @cloneofghosts said. I just fixed this, so let me know if it comes back for you, otherwise I can keep looking into this!

**Comment by afxefx** [comment]
Appreciate it and will update if the issue returns.
