### ISSUE TITLE
Units parameter seems to be ignored

### ISSUE THREAD

**Issue by andreapx** [alexander0042/pirate-weather-ha#118]
I'm using this URL: https://api.pirateweather.net/forecast/MY_API_KEY/LAT,LONG&units=**ca**&tz=Europe/Zurich but I get the temperatures in Fahrenheit and not Celsius.
Thanks!

**Comment by cloneofghosts** [comment]
The reason why the units parameter is being ignored is because you have an & in front of the units parameter when it should be a ?. So it should be ?units and not &units. The tz parameter is only accepts precise as an option as all the times are converted into the local time zone and only gets an accurate time zone if needed.

This is the URL that I use to query the API and it returns the temperatures in Celsius https://apipirateweather.net/forecast/api/lat,lon?units=ca

**Comment by andreapx** [comment]
Damn it!!! Thanks a lot!

P.s. I receve 500 or 503 right now.

**Comment by cloneofghosts** [comment]
Taking a quick look at the [status page](https://stats.uptimerobot.com/DRKqBCok2N) shows that the API is down currently. Hopefully the dev can fix the issue soon but if not you can email him at api@alexanderrey.ca.

**Comment by andreapx** [comment]
Thanks, I didn't know about the existence of that webpage!

**Comment by cloneofghosts** [comment]
Taking a look at the status page shows that everything is back up and running. If the units parameter is working for you now then feel free to close this issue.

**Comment by andreapx** [comment]
Thanks for the update!
It's all working!
