### ISSUE TITLE
daily forecast and custom:weather-card

### ISSUE THREAD

**Issue by oddboy** [alexander0042/pirate-weather-ha#13]
Hi all,

FIrst, thank you Alexander for this awesome work!   I used to use DarkSky and I was very sad when Apple bought it.  This is a fantastic alternative!

I'm trying to use this integration with the 'custom:weather-card' (https://github.com/bramkragten/weather-card), but the forecast shows 7 days of the current day.  Please take a look at the images attached.

One shows the card using PirateWeather, the other shows the card using the Env. Canada weather integration.

I'm not really sure what to do.  Are there more options to add to configuration.yaml to extend the forecast?

all the best!

Joel
![Screenshot 2021-09-16 02 26 09](https://user-images.githubusercontent.com/431818/133561228-443bc47b-995e-4fc3-843a-81da4f4c6001.png)

**Comment by oddboy** [comment]
just adding a couple other screen grabs that show the difference between the weather.home (Env. Canada) and weather.pirateweather... 

![Screenshot 2021-09-16 02 54 25](https://user-images.githubusercontent.com/431818/133564855-3d42f6b5-3b4f-437c-b81b-16cc2f3887a1.png)
![Screenshot 2021-09-16 02 54 07](https://user-images.githubusercontent.com/431818/133564857-3bd82a60-1adc-4dc7-9bc2-82db295952f1.png)

**Comment by alexander0042** [comment]
Thanks posting this! Something definitely isn't looking quite right here (getting real groundhog Day vibes), so it's worth digging into this problem!

It's looking like the main issue is that it's using hourly values instead of daily, which gives us the never ending Thursday. According to the docs for that custom card (which looks really cool!), if you're using Dark Sky as a data source, it needs to be put in daily mode (<https://github.com/bramkragten/weather-card#dark-sky>). Since the PirateWeather integration aims to be drop-in compatible with Dark Sky, then my hunch was that we need to follow this, and it seems to have worked! My config now looks like:

`weather:
  - platform: pirateweather
    api_key: <apiKey>
    mode: daily
`
and the custom card uses `weather.pirateweather` as the source entity. 

![image](https://user-images.githubusercontent.com/26213938/133617228-9e58f9de-04eb-47d1-8e6c-49cabb03fdf6.png)

Give this a go, and let me know if it fixes things!

**Comment by rgabrielson11** [comment]
Same issue here.  And, tried the fix above and it corrected the issue.

**Comment by oddboy** [comment]
Thank you!  I can confirm that solved the problem for me too!
