### ISSUE TITLE
Pirate weather integration might cause issues with cloud integration in HA

### ISSUE THREAD

**Issue by Banjer** [alexander0042/pirate-weather-ha#132]
Serveral users have issues with the cloud intergration in HA, and a common thread seems to be the use of the Pirate Weather intergration.
See https://github.com/home-assistant/core/issues/97248

**Comment by jsapede** [comment]
Got the problme here !! fucked up all my Hass install

**Comment by SiliconAvatar** [comment]
> Serveral users have issues with the cloud intergration in HA

It's not just the cloud integration, it's the cloud, hive, mobile_app, default_config that I've seen reported by many users due to this.
For me, it's the entire mobile_app integration failing to start that's most annoying.

**Comment by armdan** [comment]
same here mobile_app, default_config, smartthings. I removed the folder from Pirate Weather from custom_templates folder and everything works fine now.

**Comment by AD-Wright** [comment]
Looks like everything is just waiting on the CI to pass https://github.com/getsentry/responses/pull/659.  Obligatory xkcd: [#2347](https://xkcd.com/2347/)

**Comment by GuruPG** [comment]
> > Serveral users have issues with the cloud intergration in HA
> 
> It's not just the cloud integration, it's the cloud, hive, mobile_app, default_config that I've seen reported by many users due to this. For me, it's the entire mobile_app integration failing to start that's most annoying.

same here. had to remove pirate weather  and then do ha core rebuild in command line.

**Comment by coldkevin** [comment]
Yeah ill be ditching pirate waeather now. Completely crippled my mobile app integration. Nabu casa compeltely usesless.

**Comment by GSLaaitie** [comment]
Sucks that my home assistant was al screwed up by this. Any suggestions for another option, or when this will be solved?

**Comment by freakshock88** [comment]
Fix should be in the 2023.08 beta already, see: https://github.com/home-assistant/core/issues/97248#issuecomment-1657245539

**Comment by AD-Wright** [comment]
So sounds like if you're fine waiting until Wednesday, then the normal release of Home Assistant should resolve it, or if you want it fixed now you can switch to the Beta channel of Home Assistant.

**Comment by GSLaaitie** [comment]
Great, I can wait until Wednesday. Thanks

**Comment by liamgwallace** [comment]
I had the same issue and updated to the beta, it seems to be OK now

**Comment by alexander0042** [comment]
Team, I'm so sorry about this!! I didn't realize the severity of this issue until just now, and so I didn't get to it nearly as quickly as I should have, and it clearly resulted in a fair bit of chaos, which isn't ok. It looks like Home Assistant was amazing enough (as per usual) to have included their own compatibility shim to address this already, so the immediate issue appears to be resolved. However, still a major issue, and I'm not taking it lightly. 

While Pirate Weather can provide historic data, I can't change what's already happened, but here's my approach to learning from this:
1. Address the root incompatibility with HA to remove the need for the shim.
2. Switch my own installation to the dev channel so I'll know if there's an update issue in real time. 
3. Continue working on getting Pirate Weather up to the standard required of an official integration, so that way it'll be part of the full HA test suite. 

Thanks again for everyone's understanding here, 
Alexander

**Comment by AD-Wright** [comment]
I can confirm that updating to the latest Home Assistant (2023.8) resolves these issues.  Yay!
