### ISSUE TITLE
502 Server Error: Bad Gateway

### ISSUE THREAD

**Issue by gateriderz** [alexander0042/pirate-weather-ha#15]
Hi,

Great work on this integration, I have been using it for a few weeks now.

This morning around 2am Eastern Time, I got an error in HA with Bad Gateway:

> Unable to connect to PirateWeather. 502 Server Error: Bad Gateway for url: https://api.pirateweather.net/forecast/[apikey]/[coordinates]?units=ca

Is this related to my setup or a general issue ?

Thank you

**Comment by gateriderz** [comment]
> Hi,
> 
> Great work on this integration, I have been using it for a few weeks now.
> 
> This morning around 2am Eastern Time, I got an error in HA with Bad Gateway:
> 
> > Unable to connect to PirateWeather. 502 Server Error: Bad Gateway for url: [https://api.pirateweather.net/forecast/[apikey]/[coordinates]?units=ca](https://api.pirateweather.net/forecast/%5Bapikey%5D/%5Bcoordinates%5D?units=ca)
> 
> Is this related to my setup or a general issue ?
> 
> Thank you

This is now resolved.

**Comment by alexander0042** [comment]
Hi,
Thanks for filing this issue, and sorry about the downtime- it was due to a bad ingest file overnight, so the next model run 6 hours later resolved this it.

When I update the back end to use the National Blend of Models, I'm also going to add a fallback for this sort of situation. I've laid the groundwork for this, so should be able to implement it in the next couple months. By keeping old model results for 24 hours, it should add another layer of stability.

Thanks again for using the service, and let me know if you encounter any other issues!
