### ISSUE TITLE
Open-Meteo integration

### ISSUE THREAD

**Issue by open-meteo** [alexander0042/pirate-weather-ha#17]
Hi @alexander0042!

I was looking for ways to implement weather forecasts into Home Assistant and saw your work here. The integration into Home Assistent was frequently requested by members on HN.

I recently released Open-Meteo.com as a free non-commercial use Weather API.  Could this be of interest to you as well? It looks like you certainly have a better understanding of how to integrate it into Home Assistent.

Let me know, if I can assist

Best, Jeff

**Comment by alexander0042** [comment]
Hi Jeff,

I saw your project- it's an incredibly cool (and professional) setup you've got setup there! I really love how your website is setup, and not requiring an API key is awesome (you clearly are more optimistic about people's use/ abuse of the API than I am). 

While this project is definitely interesting (I'm super curious how you have your back-end setup, 10ms response times are incredible), I'm afraid that I'm not much use as far as the Home-Assistant integration goes. Because the PirateWeather API uses the Dark Sky syntax, it meant that I could use the existing integration with only a couple of small changes, so I'm not super familiar with how these things are put together. 

You're probably already familiar with this, but if it helps, I noticed that you're looking to add precipitation probability to the API. I found this unreasonably difficult to do, but what ended up working was wgrib2 with the ens_processing option (https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/ens_processing.html), since it spits out percentages from ensembles.

I'll definitely keep an eye on this, and I'd love to hear from you if you have any suggestions/ ideas/ questions! 

Thanks,
Alexander

**Comment by open-meteo** [comment]
Ahh... Just using the Darksky syntax makes it of course relatively easy. I am not a big fan of the darksky syntax, but it might be a chance to simplify migration also for other projects.

The API setup is relatively easy, but optimised for exactly this use-case. It is using Swift with Vapor and critical code in C. All data is however stored optimised on SSDs for direct and local access. I just spend yesterday a couple of hours to get the API code from `2.2 ms` to `1.8 ms` (in case data is the kernel cache, on average) 😄 .

Thanks for hinting me towards the ens_processing. I will soon start working this NOAA NCEP data!

Best, Jeff

**Comment by alexander0042** [comment]
Yea- I'm not a big fan of the syntax either, but it was either that or I was going to have to learn how to code client side stuff, and that seemed like a bridge too far. The restrictive thing with it is that it means that I have to generate a bunch of parameters that are a pain (looking at you, UV index), and I'm worried about adding additional ones that aren't specified. 

C makes a ton of sense here. My background is Civil Engineering, so Python was what I knew/ went with. I wanted everything to be serverless, which was cool, but definitely limiting, particularly by the speed of AWS's Elastic File System. My hope/ dream is that one day they make a high performance version of it, which would make everything much zippier!

**Comment by open-meteo** [comment]
I am a bit sceptical about serverless, lambda, AWS elastic file system, etc. Usually latency is quite bad. Especially if you have to fetch multiple resources with waiting time in between.

Right now I am struggling even with local files if they are not in the kernel cache. "Cold" reads of **all** weather variables took `60 ms`. I am now reading files in parallel with non-blocking IO to get it down to `15-30 ms`. Once data has been read and is in the kernel cache, it is down to `3 ms`. With such timings, anything that even remotely touches networking will be magnitudes slower.

Yeah, I also fear some additional parameters like UV index... But once it is once, it is done. The only limiting factor is time and my server budget...

**Comment by alexander0042** [comment]
The latency has pros and cons. It's definitely slower to fetch things compared to an SSD (or faster) disk, and until AWS introduced their elastic file system, nothing was possible anyway. With only using block back ends (S3), indexed reads are pretty well impossible, which I needed for the NetCDF setup I'm using. 

The upside it that once things are setup, the whole stack scales beautifully, which is nice. In my experience, EFS isn't fast, but it doesn't slow down between 1 and 1000+ simultaneous connections. There are eventually limits, but they're a long ways off. 

That's a really interesting process with the kernel cache. I tried parallel reads, but Python wasn't a fan of those, and eventually gave up. There's got to be some interesting stuff done on the best way to cache weather API requests, but because the underlying data is changing so frequently, and there are so many possible locations, it gets real complicated real quick!

**Comment by alexander0042** [comment]
I'm more than happy to keep chatting weather, but just to keep the issues page tidy, I'd going to close this for now. If you ever want to drop me a line, the best way to reach me is at api@alexanderrey.ca

Thanks again for reaching out, and good luck with your new service- it looks really cool ☀
