### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mlittle408** [alexander0042/pirate-weather-ha#25]
It's been like this since about 3am this morning. Is this a problem with their service or the integration?

2021-12-04 09:18:59 ERROR (SyncWorker_1) [custom_components.pirateweather.weather] Unable to connect to PirateWeather. 502 Server Error: Bad Gateway for url: https://api.pirateweather.net/forecast/[redacted api key]/[redacted location]?units=us

**Comment by alexander0042** [comment]
Thanks for alerting me to this! Turns out there was an issue in one of the input files from NOAA that cycle, so it started throwing errors until the next cycle. Really sorry about this, but I pushed an update tonight that should prevent this error from happening going forward.

Again, really sorry for the downtime, and thanks again for using this service!

**Comment by mlittle408** [comment]
No worries at all! Thanks a ton for the response and for the awesome component!
