### ISSUE TITLE
Service Down?

### ISSUE THREAD

**Issue by xvlw** [alexander0042/pirate-weather-ha#26]
Just a heads up, I think the service may be down today.

Getting Entity is unavailable in Home Assistant and when I try to pull data from https://weather.pirateweather.net/ it just circles without returning any data.

Tried on both FF and Chrome

https://i.imgur.com/PtDJjWo.png 
https://i.imgur.com/gnap1Lx.png

**Comment by alexander0042** [comment]
For once this one isn't on me (I think). Doesn't help resolve the issue unfortunately, but I'm almost sure it's related to the US-East-1 issues AWS is having today <https://status.aws.amazon.com/>. However, since I can't access the management console/ logs, I can't be sure, but for now, I'm just going to have to wait this one out 👎 

Thanks for the alert here (I also noticed, so at least my own internal alerting system is working!), and I'll update this with a root cause when I can get back in. 

Alexander

**Comment by xvlw** [comment]
Absolutely and that makes sense.

Thank you for providing us an awesome weather service.

**Comment by xvlw** [comment]
Looks like it just came back for me :)

**Comment by alexander0042** [comment]
Just to put a final coda on this, it was 100% an AWS issue, specifically with the API gateway service, which is my front end here. 

Here's a clip of 500 errors to the service, which shows the issue well:
![image](https://user-images.githubusercontent.com/26213938/145418926-74f2d2cc-bbad-49ef-8290-d1ba7acdba40.png)

Hopefully us-east-1 sorts its issues out. I'd love to become multi-region, but alas, as long as the underlying meteorological data remains on us-east-1, I'm pretty well stuck here!
