### ISSUE TITLE
Service down, or another AWS issue?

### ISSUE THREAD

**Issue by NCC1941** [alexander0042/pirate-weather-ha#27]
Much like the issue xvlw reported a few days ago that ended up being the big AWS outage, entities are showing as Unavailable in HA and https://weather.pirateweather.net/ just circles endlessly in both FF and Chrome.

According to HA, it's been unavailable for about 3 hours.

**Comment by NCC1941** [comment]
And it's back!

**Comment by alexander0042** [comment]
Hi,

Thanks for reporting this! It's good that it came back on its own here, but to try to prevent this issue in the future, I dug into the logs to see what happened here.

It turns out that there was a lingering issue from the AWS us-east-1 glitch. One of the model processing scripts was impacted, which produced a corrupted NetCDF file. This wasn't an issue for a while, but eventually when it tried to overwrite it, it broke, which created this issue. Just to handle another edge case, I've updated things to avoid this (basically force delete instead of delete), which should prevent this particular problem from re-occurring. 

Thanks again for using this service, and definitely let know if you run into any other issues or if you have ideas/suggestions! 
Alexander
