### ISSUE TITLE
API Limit

### ISSUE THREAD

**Issue by mermelmadness** [alexander0042/pirate-weather-ha#44]
I know my API key is limited to 20,000 calls per month.  This seems reasonable, but I'm curious why my system tried to make that many.  Can I lessen the frequency of the calls?
![image](https://user-images.githubusercontent.com/38080873/160489457-792e4f84-47b7-49fd-8ad8-90cc3c88d776.png)

**Comment by alexander0042** [comment]
Hi, thanks for checking out this API, and sorry for the hiccup here! 

Could quick questions to troubleshoot this- I’m assuming you’re running the home assistant integration, and are you using the weather card, sensor, or both? They’re separate API calls, which could be part of this. 

Could you also check your config file and see if there’s a scan interval set?

**Comment by mermelmadness** [comment]
Ok, I fully understand now.  Is 00:01:00 the fastest refresh the service allows?

**Comment by alexander0042** [comment]
I appreciate the enthusiasm for rapid weather refreshes! Technically (I had to check this), I have it configured to allow up to 60 calls per minute for an API key, so once per second. That would burn through the monthly bucket pretty quickly, but it would work. That being said, it's worth keeping the back-end update frequency in mind. I ingest new weather data every hour, and it has a 15 minute output frequency. I interpolate that to get the minute by minute results, which is why the data changes every minute when you call the API; however, the fundamental time resolution is probably closer to 5 minutes than 1. 

If you're interested in more details here: everything is running on AWS Lambda, and each API call causes the function to run which queries the model files and returns the formatted weather data. The reason for the cap is that each time this function runs, it bills the time and memory usage, so to make sure this didn't spiral into too large of a credit card charge for me, I have it capped. However, the setup scales really well (I stress tested it to 1,000 calls/ minute), and the cost is just the total for the month, not the rate. Eventually I'll start hitting disk IO limits, but I'm currently at 2% of the cap, so no issues there.

**Comment by alexander0042** [comment]
Sounds like a plan! Let me know how it works and if you run into any issues or weird weather data. In the next couple months, I'm also hoping to add a very rapid refresh (~5 minutes) source for current observations, which would add some benefit to quick data reads, so you should see that in an e-mail in the next couple months.
