### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by frakman1** [alexander0042/pirate-weather-ha#5]
I don't know if this is an HA integration or a PirateWeather API issue but here goes.
I signed up and subscribed to the API and added everything to HA including the API key.
 
However, the functionality that I wish to replicate from Dark Sky app was the notification I would get when it was going to rain. I would get a notification message like "Precipitation Alert ...etc." Clear and concise. Using Tasker on Android, I would take that text and broadcast it on my Google home speakers. 

Is there any way in this service to get inclement weather alerts like that?

**Comment by alexander0042** [comment]
This is as good of a spot as any! My goal is to eventually open source this, but since it’s just a bunch of Python functions tied together with a AWS scaffolding, it doesn’t really “run” on it’s own, which complicates things a little.

In any case, the service knows when it’s about to rain, thanks to the minute by minute precipitation forecast, so this is definitely possible! Do you know if those alerts came from base Home Assistant Dark Sky integration, a different one, or custom automations?

**Comment by frakman1** [comment]
I've actually never used Dark Sky Home Assistant integration. I had custom python code on my server respond to the HTTP GET from Tasker (running on Android VM) that listened and triggered off the Dark Sky notification. So to answer your question, for me, the alerts came from the Dark Sky mobile app. That's all I really want.

In fact, sorry for the stupid question but how do I actually use this HA integration? I don't see anything new listed under the Integrations tab (`http://<IP>:8123/config/integrations`) I noticed there is a new `weather.dark_sky` entity with details about Forecast when I open its details.  Since I never used the original integration, I may be missing out on how to use it and how many features are supported.

**Comment by alexander0042** [comment]
Ok, so that's interesting! It sounds like you're running it mostly relying on the app, which is a clever setup. 
I don't think the Dark Sky app is open source, so we can't modify it to pull data from PirateWeather instead; however, if you go to the "Compatibility Considerations" section on the Getting Started page (<https://pirateweather.net/getting-started>), there's instructions about how to override your DNS and point the app towards this API. 

Dark Sky might be using a private API in their app, or have some sort of validation, but if they don't, then this approach should work!

**Comment by frakman1** [comment]
Unfortunately the app doesn't work anymore. It's no longer on the Play Store and if you can sideload it, none of the services work. Can't even search for location and get message "Dark Sky is Shutdown" if you select a known location from the list.

**Comment by alexander0042** [comment]
I dug into this issue a little more, and I might have a solution for you! I got the Dark Sky app running in Anbox on my machine, and using Wireshark I can trace the calls that it's making. If you override the entry for `api.darksky.net` to `ec2-100-25-95-66.compute-1.amazonaws.com`, then the app will request data from PirateWeather. The issue however, is that the certificate is self signed, so throws an error. 

Anbox isn't rooted, so I can't install a custom certificate; however, if you have root access in your setup, you should be able to add the certificate to the store, and then Dark Sky should trust it! I'm not sure if it'll try to do some other sort of check, but this is a promising route, so let me know if you want to give it a try?

**Comment by frakman1** [comment]
Thank you.

> If you override the entry for api.darksky.net to ec2-100-25-95-66.compute-1.amazonaws.com

How do I do this?  Is this the `/etc/hosts` URL-to-IP mapping or something else?

> you should be able to add the certificate to the store

I am using PrimeOS (an Android VM) and am pretty sure I have full access. However, I'm not sure how to add the certificate to the store. I know that in Ubuntu, you do something like [this](https://askubuntu.com/a/94861). Is there an equivalent in Android or do I have to manually hack a .crt file somewhere?

**Comment by alexander0042** [comment]
I think /etc/hosts would be easiest- I just added a CNAME from `api.darksky.net` to `ec2-100-25-95-66.compute-1.amazonaws.com` (my EC2 instance). 

For the cert, there is a Android process (I tried to follow it, but ran into the rooting issue). .crt is here: <https://github.com/alexander0042/alexander0042.github.io/blob/master/nginx-selfsigned.crt>, and if primeos has a UI, then there's an option in setting to add a cert. Otherwise, there's a pretty good set of instructions here <http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets>, depending on what version of Android it's running?

**Comment by alexander0042** [comment]
I'm going to close this for now, since until I get a good device Android device to test this on, there's not much I can do here. 
Thanks again for pointing commenting though, and feel free to re-open if there's anything else that comes up here
