### ISSUE TITLE
Warning: Updating State

### ISSUE THREAD

**Issue by AlexKusnezov** [alexander0042/pirate-weather-ha#53]
Today I got this:
```
Updating state for weather.hourlyweather (<class 'custom_components.pirateweather.weather.DarkSkyWeather'>) took 0.858 seconds. Please report it to the custom component author.
```

Everything else seems to work normal

**Comment by alexander0042** [comment]
Thanks for report (and apologies for the slow response to this ticket)! So long as everything continues working normally here, I think we can safely ignore this warning for now. 0.858 seconds is a pretty typical response time, and shouldn't impact anything else here. I'm going to close this report for now, but feel free to re-open if you notice anything else cropping up.

This should also be fixed with the [new async branch](https://github.com/alexander0042/pirate-weather-ha/tree/dev-config-flow), since the system will be able to keep performing other tasks while it's updating.
