### ISSUE TITLE
Forecast is way off for whole country or so or seems

### ISSUE THREAD

**Issue by JBakers** [alexander0042/pirate-weather-ha#64]
Hey,

The Api had been quite imprecise lately.
Its been telling me sunny last couple of days, when it's been nothing but cloudy.
I tried changing locations but it keeps saying sunny, while other forecasters are more precise.

I live in the Netherlands.

**Comment by JBakers** [comment]
Its -6 degrees Celsius here now.
Pirate weather says it's minus 2.

**Comment by cloneofghosts** [comment]
The API for your location uses the GFS/GEFS global models for your location which aren't high resolution and only runs every six hours. (You can see the last run time in the flags section). The dev plans to add in NBM (National Blend of Models) sometime next year to help solve a lot of these issues. 

This issue has been brought up in a few different issues #19, #30, #48 and #50 and is definitely something that needs improving. I could be wrong here but I think once the new flow for HA has been completed improving the forecasts/current conditions should be next up.

**Comment by JBakers** [comment]
Thanks for clarifying, makes sense! I live in the southern part of The Netherlands, near the city of Eindhoven.
I took the liberty of trying out another (national) forecast integration and this seems to solve my issues with the imprecise data.
Ive disabled the pirate weather integration, but I can enable it if I can be useful for you to check the api outputs?

**Comment by alexander0042** [comment]
That helps! I took a quick look at the current conditions, and the good news is that everything seems to be working correctly. The GFS model (which is what's used in this area) is spitting out -1C (<https://spotwx.com/products/grib_index.php?model=gfs_pgrb2_0p25_f&lat=51.43597&lon=5.48533&tz=Europe/Amsterdam>), which matches Pirate Weather for this location. What's interesting is that both [Dark Sky](https://darksky.net/forecast/51.4348,5.4801/si12/en) and [Accuweather](https://www.accuweather.com/en/nl/eindhoven-airport/3510847/current-weather/3510847) are giving the same value, so there's not much difference at the moment. One thing I want to check is if you're using the "feels like" or raw temperature, since they can definitely vary quite a bit

**Comment by JBakers** [comment]
Looks like these "bigger" forecast weather sources share a common denominator, although I'm not knowledgeable enough to see what that might be.
When i look at the forecast service i am currently using, called "buienradar", it outputs much more (for me, that is) accurate information. 
See https://www.buienradar.nl/weer/Volkel/NL/2745338

The village Volkel is near the place I live, and there is a big military airport located there, and I think "Buienradar" is using the weather data from that base. 
So maybe that's why it's more accurate?

**Comment by alexander0042** [comment]
That definitely is a more local website (I had to run it though Google Translate!), and I'm not surprised they're more accurate. At the end of the day, weather is local, so a source devoted to a small area is usually better. The trouble is that they don't say where or how they get their data, so it's impossible to verify or compare what's going on in this case. What Pirate Weather aims to do is emphasize transparency, processing, and documentation, so has a somewhat different set of goals compared to your average commercial provider. 

If you don't mind running the integration for a couple weeks and tracking how it compares, I'd be super interested. I haven't had any comparisons from the Netherlands, so this would be a really interesting case study.
