### ISSUE TITLE
No module named '_bz2'

### ISSUE THREAD

**Issue by conrad66** [alexander0042/pirate-weather-ha#66]
```
Version | core-2022.12.8

Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
User | homeassistant
Virtual Environment | true
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.10.0-20-amd64
CPU Architecture | x86_64
```

After installing version 1.0
, I get the following error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 16:35:07 (1 occurrences)
Last logged: 16:35:07

Error occurred loading configuration flow for integration pirateweather: No module named '_bz2'
```

**Comment by alexander0042** [comment]
I was thinking this might be related to the 2022.12 version, but I just updated my config and since I'm not seeing anything, that doesn't seem to be it. Taking a look around the internet, there's [this unsolved issue](https://github.com/home-assistant/core/issues/43430) from Open Weather Map. Since the v1.0 update relies heavily on this logic, this is probably it.

Unfortunately, since they never identified the problematic part of the integration or a solution, there's not a ton I can do here. It seems to be environment related, which I know isn't a very useful answer.

**Comment by alexander0042** [comment]
Since there's not much I can do here, I'm going to close this for now. Let me know if you ever find a solution, and please feel free to open a new issue if anything else comes up
