### ISSUE TITLE
Sensors Unavailable

### ISSUE THREAD

**Issue by Scags104** [alexander0042/pirate-weather-ha#7]
![image](https://user-images.githubusercontent.com/9579616/122396449-fed50b00-cf45-11eb-8b0c-6ba799b15d3e.png)

Seems my sensors are down, I have one running hourly and one running daily. Been this way for about a week or so. Seen some updates come through which didn't fix the issue. Curious if I should just uninstall/reinstall through HACS?

EDIT: Note that I renamed the entities/sensors

**Comment by alexander0042** [comment]
Thanks for noticing this- I'm pretty good at catching things during the day, but overnight (for eastern time) is another issue!

It wasn't just your setup, so don't reinstall anything, and should be back now. The back end API was throwing an error for 6 hours because one of the input files was broken. So easy to diagnose the immediate cause here, root cause is trickier. Taking a look at the CloudWatch logs, and I'll try to address the main issue so it doesn't happen again (most likely due to something with the NOAA model).

**Comment by alexander0042** [comment]
Well, root cause is that the file system threw a "permission denied" error, which is bizarre, so I'm going to chalk this one up to cloud gremlins. There's a lot (lot!) of processing that goes on every 6 hours to make the input NetCDF files, so many places for something weird to happen. The code is designed not to erase the previous dataset unless it completes successfully, but apparently something slipped through here, which is an issue!

Thinking about this, I'm going to combine this issue with <https://github.com/alexander0042/pirate-weather-ha/issues/4>. Once I set things up to keep the past 48 hours worth of data on the filesystem, I'll add another block of error checks in the API retrieval code. This way, if something weird happens during the processing, the API can fall back on the previous forecast, which is slightly less accurate, but still more than adequate.

**Comment by Scags104** [comment]
Thank you as always

For the record when you said "should be back on now", ive given it some time, rebooted HA, refreshed caches on browser and ran the entity update service on it (which to my knowledge is really all i can do to help this along) and still hasnt come back online.

**Comment by alexander0042** [comment]
Shoot, that shouldn't be happening, since it's back online for me. My best guess now would be something about the API key, so if you let me know the email address you're using, I can take a look and see if that's the issue?

**Comment by Scags104** [comment]
emailed you

**Comment by Scags104** [comment]
Saw your reply - moving the conversation back here

First of all thank you again - you didnt have to do that!

Secondly, I'm surprised that HA would reach out that many times a day. Is this something that should be limited in the integration so this isn't the case? Ive seen plenty of HACS integrations where you can specify the update interval.

I'm not using the API for anything other than the HA sensor. Even if this ran once every 5 minutes (weather doesn't change that frequently does it?!) it would result in a max of 8640 calls allowing the other 1400 or so to be used by the users without hitting the max.

**Comment by alexander0042** [comment]
Don't mention it! I'm thrilled that people are finding this useful, so too many calls is a good problem to have! 

Thanks to this report, I realized the default weather card was updating every three minutes, which might have been the issue here (unless there's something overriding it on your config.yaml). I've pushed a new version <https://github.com/alexander0042/pirate-weather-ha/commit/d040d53e8bdfa00eae6248a886f678545ad34f42> that changes it to a 15 minute interval, since that's roughly what the underlying models provide, so make much more sense as a default. The integration tries to calculate an dynamic minimum rate depending on the config, which is why this might not have been noticed yet.

Thanks again for your help here, and let me know if anything else crops up!
