### ISSUE TITLE
Ozone Unit of Measurement

### ISSUE THREAD

**Issue by chicknlil** [alexander0042/pirate-weather-ha#77]
Hello @alexander0042, noticed this in my logs today:

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980
Integration: Sensor (documentation, issues)
First occurred: 7:34:28 AM (3 occurrences)
Last logged: 7:34:28 AM

Entity sensor.south_windsor_weather_ozone (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) is using native unit of measurement 'DU' which is not a valid unit for the device class ('ozone') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.south_windsor_weather_ozone_0h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) is using native unit of measurement 'DU' which is not a valid unit for the device class ('ozone') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.south_windsor_weather_ozone_47h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) is using native unit of measurement 'DU' which is not a valid unit for the device class ('ozone') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by alexander0042** [comment]
Been a while since I've had to think about ozone units, since they don't come up that much, but this is definitely an issue! It looks like for code repositories, they've removed ozone since the typical units (Dobson) aren't included: >https://github.com/home-assistant/core/pull/84791>, That seems like an lousy solution though, since it's useful data!

[Looking around](https://en.wikipedia.org/wiki/Dobson_unit), it looks like Dobson units are loosely related to heights; however, [HA expects](https://github.com/home-assistant/core/blob/8a0fb21988fe4c92a849e5af39423b7c8120ec90/homeassistant/components/sensor/const.py#L464) micrograms per cubic meter. So time for some math:

- Per [NASA](https://ozonewatch.gsfc.nasa.gov/facts/dobson_SH.html), 1 DU = 2.69x10^16 ozone molecules/ cm2.
- Ozone has a molar mass of [47.997 g/mol](https://en.wikipedia.org/wiki/Ozone).
- [Avogadro constant](https://en.wikipedia.org/wiki/Avogadro_constant) gives us 6.02214076×10^23 molecules/ mol.
- This gives us 2.69*10^16 [molecules/cm2] / 6.02214076×10^23 [molecules/mol] * 47.997 [g/mol]

And this is where it ends. I have to say that I gave this one a valiant attempt, but it's stumped me. It comes down to a fundamental issue with the units, insofar as Dobson is integrated across the entire atmosphere and the HA one isn't. There might be some sort of approximate factor I could apply, but it would be so rough to be almost useless. 

I'll kick this one back to you. I don't really want to remove the variable, but also know the warning is irritating. Maybe the solution is to try to get Dobson added to the default set of HA units?

**Comment by chicknlil** [comment]
I'm not sure I'm actively using those sensors, so I imagine I could disable them, yes?

How would I approach that HA wise?

**Comment by alexander0042** [comment]
Way easier solution (compared to me muddling around in atmospheric science!). If you've installed via HACS, then you can go to Pirate Weather on the integration page, select "configure", and then un-click "ozone" on the "monitored conditions" dropdown

**Comment by alexander0042** [comment]
Ok, long lead time here, but I think I've got a fix. Since HA still doesn't have Dobson units, I've changed the class of the Ozone sensor, which aligns with how other integrations are doing this. 

I'm going to close this issue for now, but feel free to re-open if it crops up again!
