### ISSUE TITLE
How to create the sensors?

### ISSUE THREAD

**Issue by aliekiddo** [alexander0042/pirate-weather-ha#81]
I've set up the integration (one for daily and one for hourly). I included sensors with the hourly integration but the sensors did not appear even after a reboot. I've tried adding a separate hourly instance just for the sensors and restarted HA again but they've still not appeared as entities.

When I had it all configured just in in yaml they worked. Anything I'm doing wrong?

**Comment by aliekiddo** [comment]
Logs:


Logger: homeassistant.setup
Source: setup.py:320
First occurred: 09:50:45 (1 occurrences)
Last logged: 09:50:45

Unable to prepare setup for platform pirateweather.sensor: Platform not found (Exception importing custom_components.pirateweather.sensor).



This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/pirateweather/sensor.py:216
Integration: Pirate Weather (documentation, issues)
First occurred: 09:50:45 (1 occurrences)
Last logged: 09:50:45

Unexpected exception importing platform custom_components.pirateweather.sensor
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 657, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 674, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/homeassistant/custom_components/pirateweather/sensor.py", line 216, in <module>
    device_class=SensorDeviceClass.PRECIPITATION,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PRECIPITATION

**Comment by cloneofghosts** [comment]
You're trying to add the precip_accumulation sensor and it's throwing a error right? Currently that sensor returns None if there is no accumulation for the current day instead of 0. This will be fixed in the [next update](https://github.com/alexander0042/pirate-weather-ha/issues/74#issuecomment-1409209763) and it should allow you to add the sensors then.

**Comment by alexander0042** [comment]
That might be it; however, I suspect this is probably a version thing. Do you know what version of home assistant you're running here, since it may not have the new precipitation classes?

**Comment by aliekiddo** [comment]
I've tried removing just the precipitation accumulation sensor, then all precipitation sensors, then stripped it back to only choosing the temperature sensor but still nothing.

I would agree that something to do with the version is likely - I'm running my HA on TrueNAS Core and the last compatible version is 2022.8.4 - If I want to upgrade past that I have to do some major upheaval to the machine I'm running this all on and I haven't come to the point of wanting to do that yet.

**Comment by alexander0042** [comment]
Thanks for clarifying that! What's weird is that I checked this, and the version that's has these new classes was [2021.12](https://www.home-assistant.io/blog/2021/12/11/release-202112/#updates-for-custom-integration-developers), so shouldn't be an issue for you, However, since reality begs to differ, so we're back at square 1. 

I know it's not really a solution, but in your case you might be better off using the [legacy version](https://github.com/alexander0042/pirate-weather-ha/tree/Legacy-Dark-Sky). It's not in HACS anymore, but you could either git clone or download it into your custom_components folder and configure via yaml. Other than not having the config UI there's nothing radically different about it, so would probably accomplish what you're looking for here,

**Comment by aliekiddo** [comment]
Thanks @alexander0042, I will consider going back to the the legacy version as it was working before I updated from HACS - my reason for wanting the sensors was to use them with another custom integration to get a 'temp feels like' value, but I have managed to do that with the Pirate Weather temp, humidity and wind attributes instead. 

I was also interested in seeing what the 'feels like' values your sensors provided amongst the other new bits and seeing if I could just use PW over some other HACS integrations doing things like ozone, and temp feels like separately.
