### ISSUE TITLE
Receiving prompt in log: "Configuration of Pirate Weather sensor in YAML is deprecated and can be safely removed" but has already been removed from configuration.yaml.

### ISSUE THREAD

**Issue by grantalewis** [alexander0042/pirate-weather-ha#83]
Message in the log:

``2023-02-03 13:54:02.118 WARNING (MainThread) [custom_components.pirateweather.sensor] Configuration of Pirate Weather sensor in YAML is deprecated Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file``

...but there's no longer anything pertaining to Pirate Weather in my configuration.yaml file. Could the info be elsewhere?

**Comment by alexander0042** [comment]
Thanks for using this integration and opening this issue, since that is definitely not the expected behavior! I just tested the most recent version on my end and I'm not seeing these warnings once they're removed, so definitely something strange going on here. Just as a sanity check, can you verify that there's not a rogue sensor block somewhere in either your configuration or sensor.yaml, and that you've restarted core?

**Comment by grantalewis** [comment]
Sure enough -- there was code in sensors.yaml. I thought I'd used VSCode to search all of my yaml files/folders... Anyway, thanks!
