### ISSUE TITLE
Precip Accumulation is incorrect

### ISSUE THREAD

**Issue by augster** [alexander0042/pirate-weather-ha#86]
I'm seeing some discrepancies with the precip_accumulation_Xd sensor values when compared to Merry Sky (https://merrysky.net/forecast/48.360169781921684,-116.61274232147296/us) which I believe is using the same data...

Using the same GPS coordinate, you can see that the accumulations for sunday are drastically different; 11.4in vs 4in. Is this perhaps a unit conversion bug? 11.4cm = 4.48in?

![image](https://user-images.githubusercontent.com/6400730/221234952-419e3def-1bdf-4154-8e9d-b77c2580406d.png)
![image](https://user-images.githubusercontent.com/6400730/221235050-a48bf78c-d411-438e-b26d-60d7a9256076.png)

**Comment by cloneofghosts** [comment]
If you display the sensor directly do you see the same value as the weather card?

I tested this earlier and I was getting 12mm for non-US units and 30mm for US units. I was using a Canadian location but that shouldn't matter in this case.

There definitely seems to be a bug in the integration as the API results are correct. I'll mention @alexander0042 so he can come and investigate.

**Comment by alexander0042** [comment]
I am so sorry for not getting to this one earlier- I didn't realize the extent of it at first, but it turns out I just flat out missed precipitation accumulation in the unit conversion routine, so it's always returning in SI but claiming to be whatever unit is requested. Long story short, not good!

At least it's an easy fix, so I'll push out a new version ASAP!

**Comment by alexander0042** [comment]
And it's live! Thanks again for pointing this out, and feel free to re-open if anything else comes up!
