### ISSUE TITLE
Please allow setting scan interval in config flow setup

### ISSUE THREAD

**Issue by gderber** [alexander0042/pirate-weather-ha#88]
While using the yaml setup, I had multiple sensor configurations plus the weather integration.

My ideal scenario I update the sensors with some variation of:

0-1 hr: Every 5 minutes
2-6 hrs: Every 15-30 minutes
7-24 hrs: Every hour
24-48 hrs: Every 3 hours
3 -7 days: Max 4 times a day

I tend to pick sensors depending on how frequently I'd like them updated as well.  Moon Phase I don't see any reason to update more than once a day, where as Alerts I'd like every 5 minutes.

**Comment by gderber** [comment]
Thanks! Yes, my config was imported from yaml, never thought about deleting and re-adding.

So, low priority, I still think it'd be a good enhancement to allow changing the interval after the initial configuration.

**Comment by cloneofghosts** [comment]
I've actually asked the dev about having the ability to change the interval after initial setup and the response was:

> To answer the second question, the way HA stores the data and sets things up means that it's not possible to update the key/ update interval after creation, but I should document that somewhere.

You can see #79 for more details

**Comment by gderber** [comment]
Well then, might as well close this issue.  Not sure if you add tags when closing issues.

**Comment by cloneofghosts** [comment]
@alexander0042 is the only one that can add tags to issues. Since the issue is solved you can go ahead and close this issue.

I'm just a member of the community that helps out where possible.

**Comment by gderber** [comment]
Thank you! I will

**Comment by alexander0042** [comment]
@cloneofghosts is fantastic here, so thanks again for responding to this! 

Not much to add, but it's worth mentioning that as of the new version, data updates are synchronized. This means that no matter how many integrations or sensors you have for the same location, it will only result in a single API call. Since it's all the same usage, there's no downside to updating everything according to whatever is the most frequent variable, which hopefully helps with this. 

Also wanted to add that while you can set this to update every 5 minutes, I would suggest picking a longer threshold than that. The model data that underpins this whole thing has only provides data in 15 minute increments, so while the API interpolates this down to a minute-by-minute data, there isn't much benefit to requesting data faster than that.
