### ISSUE TITLE
Sensor off by more than 20°F for several days

### ISSUE THREAD

**Issue by grantalewis** [alexander0042/pirate-weather-ha#90]
My ``sensor.pirateweather_daytime_high_temperature_0d`` sensor has been off by more than 20°F for several days.

https://i.imgur.com/hRsOzb9.png

(The highs have been in the 50s here each day this week.)

Maybe this is just a fluke, just "one of those things" that will fix itself in a day or three. But perhaps there's something I need to do on my end?

**Comment by cloneofghosts** [comment]
From looking at the graph I noticed that you've encountered the bug where between 6pm-12am on the current day it uses the highest temperature for the week instead of using the current day or current temperature. It's something that I've reported to the developer here https://github.com/alexander0042/pirateweather/issues/23 and is still in the process of being fixed.

You also mentioned that the high temperatures have been in the 50s and looking at the graph there are points where its above and below 50F. To help @alexander0042 investigate can you give us where you are roughly located and have you compared the high temperatures from PW to other sites such as Accuweather, Weather.com or your national weather service to see how well the high temperatures match up?

It could be an issue with the data or perhaps whichever model is used for your area is struggling to forecast the correct temperatures for your region which has been reported in some different issues already #64, #50 and #30.

**Comment by grantalewis** [comment]
Thanks for the reply, @cloneofghosts. I wasn't aware of the bug you mentioned, so I appreciate the input.

My location is Greer, SC, zip 29651. Here's an image from Weather Underground that shows the weather for roughly the same time frame:
https://i.imgur.com/RDFewFy.png

I also have a PWS in my yard. Here are the highs/lows for those dates:
https://i.imgur.com/V3zqTu4.png

Hope this is helpful.

**Comment by cloneofghosts** [comment]
I've had a quick look at the images and outside of the 6pm-12am range it seems pretty similar to the other images you posted but without knowing the numbers from PW it's hard to do a full comparison.

The API does store model results from the past 5ish days so it is possible to view old data for a better comparison so it's something that I could do and it'd be easier to compare.

The dev plans on switching over to using NBM instead of HRRR and should bring better results though there's no ETA on that currently. It's also possible that whatever the issue HRRR is having in your area gets sorted and starts producing better results as I do find that the accuracy can vary daily.

**Comment by cloneofghosts** [comment]
Was finally able to dig into the API and do a proper comparison between PirateWeather and using the airport station data from Wunderground. I was only able to go back two days so I included today's forecast as another comparison. From the looks of things PW and Wunderground show pretty similar results for the past few days.

| Date | PirateWeather | Wunderground |
|--------|--------|--------|
| March 23 | 77 | 79 |
| March 24 | 81 | 82 |
| March 25 | 76 | 80 | 

@grantalewis Outside of the hours where the high temperature is bugged are you still seeing the high temperature being 20F off?

**Comment by grantalewis** [comment]
It seems to have straightened itself out -- but that may be because our weather "caught up" to the strangely high readings I was getting with pirateweather. As you mention above, our temps the last couple of days have been in the upper 70s/low 80s.

It is interesting to note the graphed history of readings I was getting:

https://i.imgur.com/7ZrNqu0.png

3/18 through 3/23 almost look faked. Moving into 3/24 the graph looks much more like the data from 3/16 and 3/17 did.

**Comment by cloneofghosts** [comment]
I took a look at the forecast and the next 7 days all have similar temperatures. You still might see the bug I mentioned but won't nearly be as bad unless the temperatures vary wildly.

The dev plans on using the high temperature for the day from 6pm-12am to solve this issue. Until that happens you can leave this issue open as a reminder for him to fix the issue.
