### ISSUE TITLE
Some sensor names are not the same - not a complaint just logging so you know

### ISSUE THREAD

**Issue by 26tajeen** [alexander0042/pirate-weather-ha#95]
Maybe you already know.

[Written about it here](https://old.reddit.com/r/homeassistant/comments/121jyff/if_anyone_is_looking_for_a_replacement_for_the/)

but basically eg the daily max temperature anymore is now daytime high temperature ? 
 I had to rename them from "dark_sky Overnight Low Temperature 2d" to "sensor.dark_sky_daily_low_temperature_2d" etc

THANK YOU for this integration

**Comment by alexander0042** [comment]
Thanks for highlighting this, I had noticed this before, and should have documented it. Unfortunately, as much as I strive for Dark Sky compatibility, it's not always possible. The issue here is that Home Assistant has changed a fair bit, and one of the changes relates to the sensor names. Since I'm ultimately trying to get this merged into mainline, I have to follow their guide.

I do have a legacy branch as part of this project, which should be 100% the same as the Dark Sky sensor. You'll lose the integrated updates, units, and some other more recent developments, but the data will all be the same.

I'm going to close this for now to try to keep my issues panel clean, but absolutely feel free to comment or open again if there's anything else that comes up here!
